VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65"

  # This box was found at http://www.vagrantbox.es/
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
    ansible.verbose = "vvvv"
  end

  config.vm.define "testeNR" do |testeNR|
    testeNR.vm.box = "testeNR"
    testeNR.vm.network "private_network", ip: "172.20.20.21"
    testeNR.vm.network "forwarded_port", guest: 8080, host: 9090

  end


end

